import fs from 'node:fs/promises';
import path from 'node:path';

export const HOOK_MATCHER = 'startup|resume|clear|compact';
export const DEFAULT_COMMAND = 'npx -y get-bearings emit';
export const HOOK_TIMEOUT = 30;

const OURS = /(^|\s|\/)(npx\s+(-y\s+)?)?(get-)?bearings(\.mjs|\.cmd)?"?\s+emit(\s|$)/;

export function isOurs(hook) { return hook?.type === 'command' && typeof hook.command === 'string' && OURS.test(hook.command); }

/** `[{ group, index, hook }]` for every hook of ours in a settings object. */
export function findOurHooks(settings) {
  const out = [];
  const groups = settings?.hooks?.SessionStart;
  if (!Array.isArray(groups)) return out;
  groups.forEach((g, gi) => (g?.hooks || []).forEach((h, hi) => { if (isOurs(h)) out.push({ group: gi, index: hi, hook: h }); }));
  return out;
}

export function buildCommand({ command, budget } = {}) {
  const base = command ? `${command} emit` : DEFAULT_COMMAND;
  return budget ? `${base} --budget ${budget}` : base;
}

async function readSettings(settingsPath) {
  let text;
  try { text = await fs.readFile(settingsPath, 'utf8'); } catch (e) { if (e.code === 'ENOENT') return {}; throw e; }
  if (text.charCodeAt(0) === 0xfeff) text = text.slice(1);
  if (!text.trim()) return {};
  try { return JSON.parse(text); } catch { throw new Error(`settings file is not valid JSON, left untouched: ${settingsPath}`); }
}

async function writeSettings(settingsPath, settings) {
  await fs.mkdir(path.dirname(settingsPath), { recursive: true });
  await fs.writeFile(settingsPath, JSON.stringify(settings, null, 2) + '\n', 'utf8');
}

/** Merge our SessionStart hook into a settings file. Idempotent. Returns `{ changed, command, settingsPath }`. */
export async function installHook({ settingsPath, command, budget } = {}) {
  const settings = await readSettings(settingsPath);
  const cmd = buildCommand({ command, budget });
  const entry = { type: 'command', command: cmd, timeout: HOOK_TIMEOUT };
  const ours = findOurHooks(settings);
  if (ours.length) {
    const same = ours.every(({ group, hook }) => hook.command === cmd && settings.hooks.SessionStart[group].matcher === HOOK_MATCHER);
    if (same && ours.length === 1) return { changed: false, command: cmd, settingsPath };
    // Replace: drop every existing one of ours, then add fresh.
    await uninstallHook({ settingsPath });
    return installHook({ settingsPath, command, budget });
  }
  settings.hooks ??= {};
  settings.hooks.SessionStart ??= [];
  settings.hooks.SessionStart.push({ matcher: HOOK_MATCHER, hooks: [entry] });
  await writeSettings(settingsPath, settings);
  return { changed: true, command: cmd, settingsPath };
}

/** Remove our hooks only. Returns `{ changed }`. */
export async function uninstallHook({ settingsPath } = {}) {
  const settings = await readSettings(settingsPath);
  const ours = findOurHooks(settings);
  if (!ours.length) return { changed: false, settingsPath };
  const groups = settings.hooks.SessionStart;
  for (const g of groups) g.hooks = (g.hooks || []).filter((h) => !isOurs(h));
  settings.hooks.SessionStart = groups.filter((g) => g.hooks.length);
  if (!settings.hooks.SessionStart.length) delete settings.hooks.SessionStart;
  if (!Object.keys(settings.hooks).length) delete settings.hooks;
  await writeSettings(settingsPath, settings);
  return { changed: true, settingsPath };
}

/** The JSON a SessionStart hook prints to add context. */
export function hookOutput(markdown, outFile = 'BEARINGS.md') {
  const note = `\n_Orientation map generated by Bearings (same text as ${outFile}). Use it instead of re-listing the tree; it may lag the last edit by one session._\n`;
  return JSON.stringify({ hookSpecificOutput: { hookEventName: 'SessionStart', additionalContext: markdown + note } });
}
